### PR TITLE
Rewrite as WebExtension (FF56+) (Updated with toolbar icon & locales)

### PR DESCRIPTION
**Pull request by girst**
NOTE: the icons-feature doesn't work with Firefox 55 or lower - see [ff55](https://github.com/girst/resurrect-pages/tree/ff55) for a branch without the icons

Not everything that was in the old version has been brought over yet. This is
mainly:
 * ~~all the locales (English only currently)~~ (old locales auto converted)
 * ~~toolbar button~~ (added)
 * hotkey (Ctrl-Shift-U)
 * network error page

However, the main feature is there:    
resurrect
 * the current page
 * the link right-clicked on
 * the selected string of text

in either

 * the current
 * a new foreground tab
 * a new background tab
 * a new window

using

 * Google Cache
 * Google Cache (Text-Only)
 * The Internet Archive's Wayback Machine
 * Archive.is
 * WebCite

### CODE REVIEW

**Comment by girst** [comment]
See also: 
https://github.com/arantius/resurrect-pages/issues/26

**Comment by DaAwesomeP** [comment]
I haven't tested it yet (I will), but I think this is a great start! Are all of the context items added to the main menu, or is it a submenu?

**Comment by girst** [comment]
here's a screen shot 

screenshot

**Comment by girst** [comment]
implemented the popup

image

**Comment by arantius** [comment]
What does resurrect "the selected string of text" even mean?

**Comment by girst** [comment]
it was my attempt at replicating this: https://i.imgur.com/0ZGIu86.png

my version currently lacks the detection if it actually looks like a url. (I've got no problem with removing that feature until it's completed)

**Pull request merged**
